apiVersion: v1
kind: ConfigMap
metadata:
  name: customer1
data:
  TEXT1: Customer1_Company
  TEXT2: Welcomes You
  COMPANY: Customer1 Company Technology Pct. Ltd.

# `kubectl create -f customer1-configmap.yaml`
# You can see the data by executing `kubectl describe configmap customer1`

# You can also create ConfigMap from the literal values:
# `kubectl create configmap my-config --from-literal=key1=value1 --from-literal=key2=value2`
# And then `kubectl get configmaps my-config -o yaml`

# Use ConfigMap Inside Pods
# 1. As an Environment Variable
#    containers:
#      - name: rsvp-app
#        image: teamcloudyuga/rsvpapp
#        env:
#        - name: TEXT1
#          valueFrom:
#            configMapKeyRef:
#              name: customer1
#              key: TEXT1 # It will return Customer1_Company
# 2. As a Volume
# We can mount a ConfigMap as a Volume inside a Pod.
# For each key, we will see a file in the mount path and the content of that file becomes the respective key's value.
