apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: rsvpdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: rsvpdb

# As we did not specify any ServiceType, mongodb will have the default ClusterIP ServiceType.
# This means that the mongodb Service will not be accessible from the external world.
