apiVersion: v1
kind: Service
metadata:
  name: rsvp
  labels:
    app: rsvp
spec:
  type: NodePort # `kubectl describe service rsvp | grep NodePort:` to see the port number
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: rsvp

# You may notice that we have mentioned the `targetPort` in the ports section,
# which will forward all the requests coming on port 80 for the ClusterIP to the referenced web-port port (5000) on the connected Pods.
