apiVersion: v1
kind: Secret
metadata:
  name: my-password
type: Opaque
data:
  password: bXlzcWxwYXNzd29yZAo= # `echo mysqlpassword | base64`

# To decode: `echo "bXlzcWxwYXNzd29yZAo=" | base64 --decode`

# To use the Secret(s) inside the Pod(s):

# 1. Using Secrets as Environment Variables
# containers:
#       - image: wordpress:4.7.3-apache
#         name: wordpress
#         env:
#         - name: WORDPRESS_DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: my-password
#               key: password # Returns mysqlpassword

# 2. Using Secrets as Files from a Pod
# We can also mount a Secret as a Volume inside a Pod.
# A file would be created for each key mentioned in the Secret, whose content would be the respective value. 
