apiVersion: v1 # Essentially http://127.0.0.1:8001/api/v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx

# lmaly@lmaly  ~/Projects/kubernetes-cheatsheet/minikube-hellonode   master  kubectl get services
# NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
# kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP        14d
# web-service   NodePort    10.102.75.113   <none>        80:31401/TCP   52s
# Mapping 80:31401 means if we connect to the node 10.102.75.113 on that port 31401, our requests will be forwarded to the ClusterIP 10.96.0.1 on port 80.
